title: Wes Kennedy
email: wk@wes.today
description: >- # this means to ignore newlines until "baseurl:"
  technical product strategist. adhd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-glossary_tooltip

minima:
  skin: solarized-dark

permalink: /:slug

social:
  twitter: wesdottoday
  github: wesdottoday

paginate: 8
paginate_path: "/:num"

collections:
  garden:
    output: true
    #sort_by: 
