title: Wes Kennedy

url: https://wes.today
baseurl:

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 7
paginate_path: "/:title"

theme: no-style-please
