title: Wes Kennedy
pronouns: "he/him"
url: https://wes.today
baseurl:

email: hello@wes.today
description: "I'm just a guy who does things from time to time. I father, drink whisky, collect live music, technically market, and hack on things."
github_username:  wesdottoday

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

remote_theme: riggraz/no-style-please
theme: no-style-please

permalink: /:title/

theme_config:
  appearance: 'auto'
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home pag