title: Wes Kennedy
email: wk@wes.today
description: >- # this means to ignore newlines until "baseurl:"
  technical product strategist. adhd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

minima:
  skin: solarized-dark
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/wesdottoday" }
    - { platform: gitlab,         user_url: "https://gitlab.wes.today/wk" }
    - { platform: mastodon,       user_url: "https://hachyderm.io/web/@wesdottoday" }

permalink: "/:title/"

paginate: 8
paginate_path: "/:num"

collections:
  garden:
    output: true
  stream:
    output: true
