title: Wes Kennedy
pronouns: "he/him"
url: https://wes.today
baseurl:
author: Wes Kennedy
email: hello@wes.today
description: "I'm just a guy who does things from time to time. I'm a husband & father, a whisky drinker, a live music archivist, and a technical marketer."
github_username:  wesdottoday

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-time-to-read

remote_theme: riggraz/no-style-please
theme: no-style-please

permalink: /:title/

theme_config:
  appearance: 'auto'
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

collections:
  refs:
    output: true