title: Wes Kennedy

url: https://wes.today
baseurl:

email: hello@wes.today
description: wes's thoughts
github_username:  wesdottoday

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: riggraz/no-style-please
theme: no-style-please

permalink: /:title/

theme_config:
  appearance: 'auto'
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home pag