# Light Mode site colors
light_colors:
  background: '#F1F5F2'
  background_alt: '#A9BCD0'
  text: '#595959'
  text_alt: '#212738'
  accent: '#E0AFA0'

# Dark Mode site colors
dark_colors:
  background: '#595959'
  background_alt: '#212738'
  text: '#F1F5F2'
  text_alt: '#A9BCD0'
  accent: '#E0AFA0'

# Font settings
font:
  body_font:
  title_font:
  regular_weight: 'normal'
  bold_weight: 'bold'